### PR TITLE
Add support for surveys and in-app notifications

### PR DESCRIPTION
**Pull request by inakiabt**
Add script to compile storyboards located on “ios/platform/iphone”
Update storyboards from Mixpanel SDK 2.6.0

Tested only on iOS 8 (SDK 3.4.1 and 3.4.0).

Fixes https://github.com/hyperlab/TiMixpanel/issues/4

### CODE REVIEW

**Comment by mrlundis** [comment]
@inakiabt and @timanrebel Would you mind taking a look at my changes in 995e2e9, in order to verify that things still work as expected? 

If so, then we can finally go ahead and get this merged! :)

**Comment by inakiabt** [comment]
@mrlundis I've just tested it and it works!
But there is an issue with the SDK assets:
If they are located, before build the module, in `assets` folder, the app won't find them (no crash, but no images).
If they are located in `platform/iphone` folder, they will be shown in the app. But, after build the module, the assets will be copied to `assets` too.

timixpanel-issue

I think it's not bad, but do you know how to avoid this duplication?

**Comment by inakiabt** [comment]
Any update on this?

**Comment by mrlundis** [comment]
@inakiabt It seems weird that the assets should end up in both of those places.. 

I've found that you more or less have to delete the entire build folder between builds in order to get a clean build. Doing so might help with the duplication issue. Otherwise I guess this is something we will have  to live with for a while, until someone finds a way to clean up the dupes.

**Comment by inakiabt** [comment]
@mrlundis you're right!
I tested it on a clean build and it's not duplicating the assets.
I updated the PR moving the images from `assets` to `platform/iphone`.

**Comment by mrlundis** [comment]
Boom! Thank you so much for helping out with this @inakiabt. :D

**Comment by brianjd** [comment]
Great work guys!

**Pull request merged**
