### PR TITLE
Calling getPeople().identify in Android

### PR DESCRIPTION
**Pull request by tbjers**
MixPanel's Android library requires a call to `getPeople().identify()` in order to work correctly with user profiles, otherwise they simply get stuck in the user's sharedPrefs and never make it to Mixpanel.

I do not know how to actually compile the Android module since the project's configuration seems to be a bit borked, `ant` gives me errors, and I wasn't able to compile in Titanium Studio either. Can you maybe do that last bit and add an updated version?

### CODE REVIEW

**Comment by mrlundis** [comment]
Good catch!

I'm a bit concerned about what will happen if you call `getPeople().identify()` though, when you do not intend to use the mixpanel people features.. I.e. that you'll need to pay for a people plan, even if you do not use those features. But maybe thats a non-issue? 

To build the module for Android you'll need to set up a `.classpath`-file. Take a look at  `.classpath.example` for an idea of what goes where. You might need to update the version numbers and paths a bit to match changes to the repository and your local environment.

**Comment by tbjers** [comment]
Thanks!

The iOS library apparently bakes the regular identify and the people identify call together already. I am unsure why their Android SDK doesn't do the same thing. You won't need to pay for a people plan as long as you are not setting/updating people profile data.

I will give compiling this a whirl and hopefully have something ready today. I just haven't done much Java compiling in the last decade...

**Comment by tbjers** [comment]
Question, the `build.properties` file uses `3.2.2.GA`, do I have to use that version, or will it be safe to compile with `3.5.0.GA`?

**Comment by tbjers** [comment]
I have compiled and added android version 0.8 of TiMixpanel.

**Comment by joeatwork** [comment]
@mrlundis You'll only create people profiles (and thus only be charged for people records) if you call `getPeople().set()` or otherwise edit the record you've identified for.

**Comment by mrlundis** [comment]
Sweet! Thank you @tbjers and @joeatwork!

**Pull request merged**
